worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    gzip  on;

    server {
      listen 80;
      listen [::]:80;
      server_name moup.io www.moup.io;
      return 301 https://$host$request_uri;
    }

    server {
        listen       443 ssl;
        server_name  moup.io www.moup.io;
        ssl_certificate      /usr/share/nginx/fullchain1.pem;
        ssl_certificate_key  /usr/share/nginx/privkey1.pem;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
    }
}
